name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash --noprofile --norc -xeo pipefail {0}

jobs:

  build_wheel:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install cibuildwheel
        run: python -m pip install -U cibuildwheel

      - name: Build wheels
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_ALL_LINUX: yum install -y libudev-devel
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wheels (${{ runner.os }})
          path: wheelhouse/*

      - name: Sanity check
        run: |
          python -m venv venv
          ./venv/bin/pip install -f wheelhouse pyusb_libusb1_backend
          ./venv/bin/python -I check.py
